### ISSUE TITLE
Error in double(N *Ml):vector size cannot be NAIn addition: warning message:In N * Ml : NAs produced by integer overflowCalled 

### ISSUE THREAD

**Issue by leslieyoungwei** [BavoDC/val.prob.ci.2#5]
Hello, I'm using this function to plot a calibration curve.
The function works fine when I sample 30,000 people, then I get this problem when I use the full population

```
g4<-va.prob.ci.2(data$predl, data$y)
Error in double(N *Ml):vector size cannot be NA
In addition: warning message:
In N * Ml : NAs produced by integer overflow
Called from:double(N * M1)
Browse[1]>
```

Can you help me with this problem please, thanks!

**Comment by BavoDC** [comment]
Hi Wei,

My apologies for the late response, I was out of office. 

Have you updated the package to its latest version?

One of the issues could be the distribution of your predicted values. There is a detailed thread here: [https://github.com/BavoDC/CalibrationCurves/issues/7](https://github.com/BavoDC/CalibrationCurves/issues/7).

Could you go over the comments and see if you have a similar problem? Please, do give your comments in this thread, so that I can closely monitor the issue and hopefully help you. This seems to be a recurring issue and with your help, I can further improve the package.

Best,

Bavo.
